#!/usr/bin/env python3
"""
Deterministic module doc generator — reads docs/index.json, writes docs/modules/*.md.

No LLM calls. Prose is templated from scan stats (LOC, churn, imports) and
provenance graph (commits, co-change, reach) when available.
"""

import json
import os
import re
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE / "scripts"))

from graph_lib import provenance_for_file  # noqa: E402

FIXTURE_ROOT = HERE / "test-repos"


def resolve_docs(repo):
    repo = repo.resolve()
    if repo == HERE.resolve():
        return HERE / "docs"
    try:
        repo.relative_to(FIXTURE_ROOT)
        return repo / "docs"
    except ValueError:
        return HERE / "docs"


def docs_for_docgen():
    target = os.environ.get("TARGET_REPO")
    if target:
        return resolve_docs(Path(target).expanduser().resolve())
    return HERE / "docs"


def slugify(path):
    return re.sub(r"[^a-zA-Z0-9._-]+", "-", path).strip("-") or "root"


def module_key(path):
    if path.endswith("/__init__.py"):
        return path[: -len("/__init__.py")]
    if path.endswith(".py"):
        return path[:-3]
    return path


def file_path_for_module(mod, file_meta):
    if mod in file_meta:
        return mod
    for candidate in (f"{mod}.py", f"{mod}/__init__.py"):
        if candidate in file_meta:
            return candidate
    return mod


def build_graph(edges):
    incoming = defaultdict(list)
    outgoing = defaultdict(list)
    for e in edges:
        outgoing[e["source"]].append(e["target"])
        incoming[e["target"]].append(e["source"])
    return incoming, outgoing


def render_provenance_section(path, index):
    graph = index.get("graph") or {}
    if not graph.get("edges"):
        return ["## Provenance", "", "_Run `github_intel.py` to populate graph data._", ""]

    info = provenance_for_file(path, index, reach_depth=2)
    lines = ["## Provenance", ""]

    commits = info["commits"]
    if commits:
        lines.append("### Recent commits")
        lines.append("")
        for commit in commits:
            lines.append(
                f"- `{commit.get('sha', '?')}` ({commit.get('date') or '—'}) "
                f"{commit.get('message', '')[:80]}"
            )
        lines.append("")

    co_changed = info["co_changed"]
    if co_changed:
        lines.append("### Co-changed with")
        lines.append("")
        for partner, weight in co_changed[:8]:
            lines.append(f"- `{partner}` (weight {weight})")
        lines.append("")

    reach = info["reach"].get("reachable") or []
    file_reach = [r for r in reach if r.get("kind") == "file"][:8]
    if file_reach:
        lines.append("### Reach (2-hop)")
        lines.append("")
        for item in file_reach:
            lines.append(f"- `{item['label']}` via {item.get('via') or '?'} (depth {item['depth']})")
        lines.append("")

    if len(lines) <= 3:
        lines.append("_No provenance edges for this file yet._")
        lines.append("")

    return lines


def render_module(mod, meta, incoming, outgoing, index):
    path = file_path_for_module(mod, {f["path"]: f for f in index.get("files", [])})
    lines = [
        f"# `{mod}`",
        "",
        "| Metric | Value |",
        "| --- | --- |",
        f"| Language | {meta['lang']} |",
        f"| LOC | {meta['loc']} |",
        f"| Commits | {meta['commits']} |",
        f"| Last commit | {meta.get('last_commit') or '—'} |",
        "",
    ]
    if incoming[mod]:
        lines += ["## Imported by", ""]
        for src in sorted(set(incoming[mod]))[:20]:
            lines.append(f"- `{src}`")
        lines.append("")
    if outgoing[mod]:
        lines += ["## Imports", ""]
        for tgt in sorted(set(outgoing[mod]))[:20]:
            lines.append(f"- `{tgt}`")
        lines.append("")

    lines.extend(render_provenance_section(path, index))

    lines += [
        "---",
        "_Auto-generated by `docgen.py` from `docs/index.json`. Do not edit by hand._",
        "",
    ]
    return "\n".join(lines)


def main():
    docs = docs_for_docgen()
    index_path = docs / "index.json"
    out = docs / "modules"
    if not index_path.is_file():
        raise SystemExit(f"missing {index_path}; run scan.py first")

    index = json.loads(index_path.read_text())
    incoming, outgoing = build_graph(index.get("edges", []))
    file_meta = {f["path"]: f for f in index.get("files", [])}

    py_modules = sorted(
        module_key(f["path"])
        for f in index.get("files", [])
        if f["lang"] == "Python" and f["path"].endswith(".py")
    )

    out.mkdir(parents=True, exist_ok=True)
    written = 0
    for mod in py_modules:
        meta = file_meta.get(
            mod if mod.endswith(".py") else f"{mod}/__init__.py",
            file_meta.get(f"{mod}.py"),
        )
        if not meta:
            continue
        path = out / f"{slugify(mod)}.md"
        path.write_text(render_module(mod, meta, incoming, outgoing, index))
        written += 1

    print(f"wrote {written} module docs under {out}")


if __name__ == "__main__":
    main()
